AWSTemplateFormatVersion: '2010-09-09'
Description: Crear un rol IAM con acceso completo a EC2, S3, RDS y DynamoDB

Resources:
  EC2FullAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2Full
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonRDSFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
