AWSTemplateFormatVersion: '2010-09-09'
Description: Crear un S3 bucket y aplicar una política

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: s3bucketnameparaprobarladynamodbfotosymas

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowS3ReadAccess'
            Effect: 'Allow'
            Principal:
              AWS: 'arn:aws:iam::621125127298:role/EC2Full'
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
